### ISSUE TITLE
Update scancode version

### ISSUE THREAD

**Issue by persi0815** [fosslight/fosslight_source_scanner#171]
**Is your feature request related to a problem? Please describe.**
A new version of scancode-toolkit has been released. It is currently set to 32.0.2, but version 32.2.1 was released on July 1, 2024. So, I'm trying to upgrade the version.
https://github.com/nexB/scancode-toolkit/releases

**Describe the solution you'd like**
Scancode-toolkit version upgrade.

**Comment by soimkim** [comment]
ScanCode 를 >=32.2.0로 업데이트하여 본 이슈 Close합니다.
